extends Node


signal language_changed


const DEFAULT_LANGUAGE: String = "en"
const SETTINGS_SECTION: String = "language"
const SETTINGS_KEY: String = "code"

const TRANSLATIONS: Dictionary = {
	"en": {
		"language.tooltip": "Change language",
		"language.title": "LANGUAGE",
		"language.english": "ENGLISH",
		"language.portuguese": "PORTUGUÊS",
		"menu.play": "PLAY",
		"menu.quick_play": "QUICK PLAY",
		"menu.quick_play_tooltip": "Your last drawing",
		"menu.quick_play_error": "Could not load the last drawing. Use PLAY to draw a new one.",
		"menu.best_wave": "BEST WAVE: %d",
		"menu.quit": "QUIT",
		"menu.character_creator_error": "Could not open Character Creator. Check the project files.",
		"audio.tooltip": "Sound",
		"audio.title": "SOUND",
		"audio.volume": "SOUND: %d%%",
		"audio.music": "MUSIC: %d%%",
		"menu.credits": "CREDITS",
		"credits.title": "CREDITS",
		"credits.game": "GAME",
		"credits.game_line": "Blank Canvas, by Imperial Bay",
		"credits.font": "FONT",
		"credits.font_line": "Press Start 2P, SIL Open Font License",
		"credits.sprites": "SPRITES",
		"credits.sprites_line": "Enemy art from third-party packs",
		"credits.audio": "AUDIO",
		"credits.audio_line": "Sound effects made for this game",
		"credits.music_line": "Music: Juhani Junkala (CC0)",
		"credits.thanks": "THANKS",
		"credits.thanks_line": "To everyone who played and gave feedback",
		"audio.mute": "MUTE",
		"audio.unmute": "UNMUTE",
		"menu.settings": "SETTINGS",
		"pause.settings": "SETTINGS",
		"settings.title": "SETTINGS",
		"settings.tab_general": "GENERAL",
		"settings.tab_controls": "CONTROLS",
		"settings.fullscreen": "FULLSCREEN",
		"settings.screen_shake": "SCREEN SHAKE",
		"settings.damage_numbers": "DAMAGE NUMBERS",
		"settings.erase_save": "ERASE SAVE DATA",
		"settings.erase_confirm": "CONFIRM ERASE?",
		"settings.erase_done": "SAVE DATA ERASED",
		"settings.on": "ON",
		"settings.off": "OFF",
		"settings.controls_reset": "RESET CONTROLS",
		"settings.press_key": "PRESS A KEY",
		"settings.mouse_button": "MOUSE %d",
		"settings.back": "BACK",
		"settings.action_move_up": "MOVE UP",
		"settings.action_move_down": "MOVE DOWN",
		"settings.action_move_left": "MOVE LEFT",
		"settings.action_move_right": "MOVE RIGHT",
		"settings.action_fire": "SHOOT",
		"settings.action_dash": "DASH",
		"hud.wave_banner": "WAVE %d",
		"hud.boss_banner": "BOSS WAVE",
		"creator.character_title": "CREATE YOUR CHARACTER",
		"creator.ability_title": "DRAW YOUR ABILITY",
		"creator.colors": "COLORS",
		"creator.custom_color": "CUSTOM COLOR",
		"creator.custom_empty": "EMPTY SLOT",
		"creator.custom_color_added": "Custom color added to the palette.",
		"creator.color_title": "PICK A COLOR",
		"creator.color_use": "USE",
		"creator.tool": "TOOL: %s",
		"creator.tool_pencil": "PENCIL",
		"creator.tool_bucket": "BUCKET",
		"creator.tool_picker": "COLOR PICKER",
		"creator.tool_picker_hint": "COLOR PICKER — ALT + CLICK",
		"creator.tool_line": "LINE",
		"creator.tool_rectangle": "RECTANGLE",
		"creator.tool_ellipse": "ELLIPSE",
		"creator.tool_spray": "SPRAY",
		"creator.fill_shapes": "FILL SHAPES",
		"creator.color_picked": "Color picked from the canvas.",
		"creator.code": "CODE",
		"creator.code_placeholder": "PASTE A CODE",
		"creator.copy": "COPY",
		"creator.paste": "PASTE",
		"creator.load": "LOAD",
		"creator.code_copied": "Code copied! Share it with anyone.",
		"creator.code_loaded": "Drawing loaded from the code.",
		"creator.code_invalid": "This code is not a Blank Canvas drawing.",
		"creator.code_empty": "Paste a code in the field first.",
		"creator.code_copy_failed": "The browser blocked the copy. Select the code and press Ctrl+C.",
		"creator.code_copy_prompt": "Press Ctrl+C to copy your code, then close this box",
		"creator.code_copy_manual": "Your code opened in a box — press Ctrl+C there to copy it.",
		"creator.code_paste_failed": "Nothing was pasted. You can also type the code in the field.",
		"creator.code_paste_prompt": "Paste your Blank Canvas code",
		"creator.brush": "BRUSH: %d",
		"creator.eraser": "ERASER",
		"creator.clear": "CLEAR",
		"creator.undo": "UNDO",
		"creator.redo": "REDO",
		"creator.confirm": "CONFIRM",
		"creator.back_menu": "BACK TO MENU",
		"creator.back_character": "BACK TO CHARACTER",
		"creator.cancel": "CANCEL",
		"creator.pixels": "OUTLINE: %d / %d",
		"creator.canvas_cleared": "Canvas cleared. Use UNDO to restore it.",
		"creator.draw_character_first": "Draw something before confirming!",
		"creator.character_loaded": "Previous drawing loaded. Edit it or confirm to continue.",
		"creator.draw_new_ability": "Draw your new ability!",
		"creator.draw_ability_first": "Draw your ability before confirming!",
		"creator.ability_too_large": "Outline too large: %d / %d. Only the outline counts — filling it in is free.",
		"creator.arena_error": "Could not open the Arena. Check that scenes/game/arena.tscn exists.",
		"creator.ability_loaded": "Previous ability loaded. Edit it or confirm to continue.",
		"creator.shot_needed": "Choose a shot type to continue.",
		"shot.title": "CHOOSE YOUR SHOT",
		"shot.pick_one": "PICK ONE TO CONTINUE",
		"shot.locked": "NEW ABILITIES KEEP YOUR FIRST SHOT TYPE",
		"shot.back": "KEEP DRAWING",
		"shot.confirm": "CONFIRM",
		"shot.standard": "STANDARD",
		"shot.standard_info": "Curves into enemies near the end.",
		"shot.charge": "CHARGE",
		"shot.charge_info": "Hold to grow it. Short range.",
		"shot.rapid": "RAPID",
		"shot.rapid_info": "Weak, but fast and far.",
		"shot.damage": "DMG",
		"shot.range": "RANGE",
		"shot.rate": "RATE",
		"stats.life": "HP",
		"stats.damage": "DMG",
		"stats.rate": "RATE",
		"stats.pierce": "PIERCE",
		"stats.size": "SIZE",
		"stats.speed": "SPEED",
		"stats.range": "RANGE",
		"stats.dash": "DASH",
		"stats.move": "MOVE",
		"stats.pickup": "MAG",
		"stats.per_second": "%s/S",
		"stats.seconds": "%sS",
		"perk.short.vampirism": "VAMPIRE",
		"perk.short.ricochet": "BOUNCE",
		"perk.short.critical": "CRIT",
		"perk.short.explosion": "BLAST",
		"perk.short.shards": "SHARDS",
		"perk.short.overcharge": "OVERLOAD",
		"perk.short.poison": "POISON",
		"perk.short.focus": "FOCUS",
		"perk.short.momentum": "MOMENTUM",
		"perk.vampirism": "VAMPIRISM",
		"perk.vampirism_info": "Hits steal 3% of enemy max HP",
		"perk.ricochet": "RICOCHET",
		"perk.ricochet_info": "Bounces once, +1 per pierce",
		"perk.critical": "CRITICAL",
		"perk.critical_info": "25% crits, more with speed",
		"perk.explosion": "BLAST",
		"perk.explosion_info": "Full charge blasts; size = area",
		"perk.shards": "SHARDS",
		"perk.shards_info": "Hits burst shards; + per shot",
		"perk.overcharge": "OVERCHARGE",
		"perk.overcharge_info": "Hold past full: up to +60% dmg",
		"perk.poison": "VENOM",
		"perk.poison_info": "Hits poison; stacks with rate",
		"perk.focus": "FOCUS",
		"perk.focus_info": "Same foe: +8% dmg per hit",
		"perk.momentum": "MOMENTUM",
		"perk.momentum_info": "Fire 40% faster while moving",
		"hud.hp": "HP: %d / %d",
		"hud.wave": "WAVE: %d",
		"hud.enemies": "ENEMIES: %d",
		"hud.controls_hint": "SHOOT: CLICK   DASH: SPACE",
		"upgrade.max_hp": "MAX HP +45",
		"upgrade.move_speed": "MOVE SPEED +20%",
		"upgrade.pickup": "PICKUP RANGE +60%",
		"flask.slots_full": "SLOTS FULL",
		"flask.zigzag": "ZIGZAG SHOTS",
		"flask.rush": "RUSH",
		"flask.burst": "BURST",
		"flask.orbit": "CHASER",
		"creator.palettes": "PALETTES: %d",
		"creator.flask_slots": "FLASKS: %d/%d",
		"creator.buy_slot": "BUY SLOT (1)",
		"creator.slot_bought": "One more flask slot unlocked.",
		"creator.no_palettes": "Beat a boss to earn a palette.",
		"creator.slots_maxed": "All flask slots unlocked.",
		"pause.title": "PAUSED",
		"pause.resume": "RESUME",
		"pause.restart": "RESTART",
		"pause.menu": "MENU",
		"progression.wave_complete": "WAVE %d COMPLETE!",
		"progression.choose_path": "PICK AN UPGRADE TO CONTINUE",
		"progression.upgrade_ability": "UPGRADE ABILITY",
		"progression.upgrade_info": "CHOOSE 1 OF 3 RANDOM UPGRADES",
		"progression.new_ability": "CREATE NEW ABILITY",
		"progression.new_ability_info": "DRAW A NEW PROJECTILE (MAX 100 PIXELS)",
		"progression.choose_upgrade": "CHOOSE AN UPGRADE",
		"progression.back": "BACK",
		"progression.reroll": "REROLL",
		"progression.need_ink": "YOU NEED %d MORE DROPS",
		"upgrade.damage": "DAMAGE +35%",
		"upgrade.cooldown": "COOLDOWN -15%",
		"upgrade.count": "+1 PROJECTILE",
		"upgrade.size": "SIZE +30%",
		"upgrade.pierce": "PIERCE +1",
		"upgrade.speed": "SPEED +20%",
		"upgrade.dash": "DASH COOLDOWN -40%",
		"ability.name": "ABILITY %d",
		"game_over.wave_reached": "WAVE REACHED: %d",
		"game_over.best_wave": "BEST: %d",
		"game_over.new_record": "NEW RECORD!",
		"game_over.coverage": "CANVAS PAINTED: %d%%",
		"game_over.retry": "RETRY",
		"game_over.new_drawing": "NEW DRAWING",
		"game_over.save_scenario": "SAVE CANVAS",
		"game_over.menu": "MENU",
		"scenario.final_canvas": "FINAL CANVAS",
		"scenario.no_canvas": "NO CANVAS AVAILABLE",
		"scenario.press_escape": "PRESS ESC TO GO BACK",
		"scenario.saved_to": "SAVED TO: %s",
		"scenario.downloaded": "DOWNLOADED BY BROWSER: %s",
	},
	"pt_BR": {
		"language.tooltip": "Mudar idioma",
		"language.title": "IDIOMA",
		"language.english": "INGLÊS",
		"language.portuguese": "PORTUGUÊS",
		"menu.play": "JOGAR",
		"menu.quick_play": "JOGO RÁPIDO",
		"menu.quick_play_tooltip": "Seu último desenho",
		"menu.quick_play_error": "Não foi possível carregar o último desenho. Use JOGAR para desenhar outro.",
		"menu.best_wave": "MELHOR WAVE: %d",
		"menu.quit": "SAIR",
		"menu.character_creator_error": "Não foi possível abrir o Criador de Personagem. Verifique os arquivos do projeto.",
		"audio.tooltip": "Som",
		"audio.title": "SOM",
		"audio.volume": "SOM: %d%%",
		"audio.music": "MÚSICA: %d%%",
		"menu.credits": "CRÉDITOS",
		"credits.title": "CRÉDITOS",
		"credits.game": "JOGO",
		"credits.game_line": "Blank Canvas, por Imperial Bay",
		"credits.font": "FONTE",
		"credits.font_line": "Press Start 2P, SIL Open Font License",
		"credits.sprites": "SPRITES",
		"credits.sprites_line": "Arte dos inimigos de pacotes de terceiros",
		"credits.audio": "ÁUDIO",
		"credits.audio_line": "Efeitos sonoros feitos para este jogo",
		"credits.music_line": "Música: Juhani Junkala (CC0)",
		"credits.thanks": "OBRIGADO",
		"credits.thanks_line": "A quem jogou e mandou retorno",
		"audio.mute": "MUDO",
		"audio.unmute": "COM SOM",
		"menu.settings": "OPÇÕES",
		"pause.settings": "OPÇÕES",
		"settings.title": "OPÇÕES",
		"settings.tab_general": "GERAL",
		"settings.tab_controls": "CONTROLES",
		"settings.fullscreen": "TELA CHEIA",
		"settings.screen_shake": "TREMOR DE TELA",
		"settings.damage_numbers": "NÚMEROS DE DANO",
		"settings.erase_save": "APAGAR DADOS",
		"settings.erase_confirm": "CONFIRMAR?",
		"settings.erase_done": "DADOS APAGADOS",
		"settings.on": "SIM",
		"settings.off": "NÃO",
		"settings.controls_reset": "RESTAURAR PADRÃO",
		"settings.press_key": "APERTE UMA TECLA",
		"settings.mouse_button": "MOUSE %d",
		"settings.back": "VOLTAR",
		"settings.action_move_up": "ANDAR PARA CIMA",
		"settings.action_move_down": "ANDAR PARA BAIXO",
		"settings.action_move_left": "ANDAR PARA ESQUERDA",
		"settings.action_move_right": "ANDAR PARA DIREITA",
		"settings.action_fire": "ATIRAR",
		"settings.action_dash": "DASH",
		"hud.wave_banner": "WAVE %d",
		"hud.boss_banner": "WAVE DE CHEFE",
		"creator.character_title": "CRIE SEU PERSONAGEM",
		"creator.ability_title": "DESENHE SUA HABILIDADE",
		"creator.colors": "CORES",
		"creator.custom_color": "COR PERSONALIZADA",
		"creator.custom_empty": "ESPAÇO VAZIO",
		"creator.custom_color_added": "Cor personalizada adicionada à paleta.",
		"creator.color_title": "ESCOLHA UMA COR",
		"creator.color_use": "USAR",
		"creator.tool": "FERRAMENTA: %s",
		"creator.tool_pencil": "LÁPIS",
		"creator.tool_bucket": "BALDE",
		"creator.tool_picker": "CONTA-GOTAS",
		"creator.tool_picker_hint": "CONTA-GOTAS — ALT + CLIQUE",
		"creator.tool_line": "LINHA",
		"creator.tool_rectangle": "RETÂNGULO",
		"creator.tool_ellipse": "ELIPSE",
		"creator.tool_spray": "SPRAY",
		"creator.fill_shapes": "PREENCHER",
		"creator.color_picked": "Cor capturada do quadro.",
		"creator.code": "CODIGO",
		"creator.code_placeholder": "COLE UM CÓDIGO",
		"creator.copy": "COPIAR",
		"creator.paste": "COLAR",
		"creator.load": "CARREGAR",
		"creator.code_copied": "Código copiado! Compartilhe com quem quiser.",
		"creator.code_loaded": "Desenho carregado do código.",
		"creator.code_invalid": "Esse código não é um desenho do Blank Canvas.",
		"creator.code_empty": "Cole um código no campo primeiro.",
		"creator.code_copy_failed": "O navegador bloqueou a cópia. Selecione o código e aperte Ctrl+C.",
		"creator.code_copy_prompt": "Aperte Ctrl+C para copiar seu código e feche esta caixa",
		"creator.code_copy_manual": "Seu código abriu numa caixa — aperte Ctrl+C lá para copiar.",
		"creator.code_paste_failed": "Nada foi colado. Você também pode digitar o código no campo.",
		"creator.code_paste_prompt": "Cole aqui o código do Blank Canvas",
		"creator.brush": "PINCEL: %d",
		"creator.eraser": "BORRACHA",
		"creator.clear": "LIMPAR",
		"creator.undo": "DESFAZER",
		"creator.redo": "REFAZER",
		"creator.confirm": "CONFIRMAR",
		"creator.back_menu": "VOLTAR AO MENU",
		"creator.back_character": "VOLTAR AO PERSONAGEM",
		"creator.cancel": "CANCELAR",
		"creator.pixels": "CONTORNO: %d / %d",
		"creator.canvas_cleared": "Quadro limpo. Use DESFAZER para recuperar.",
		"creator.draw_character_first": "Desenhe algo antes de confirmar!",
		"creator.character_loaded": "Desenho anterior carregado. Edite ou confirme para continuar.",
		"creator.draw_new_ability": "Desenhe sua nova habilidade!",
		"creator.draw_ability_first": "Desenhe sua habilidade antes de confirmar!",
		"creator.ability_too_large": "Contorno grande demais: %d / %d. Só o contorno conta — preencher é de graça.",
		"creator.arena_error": "Não foi possível abrir a arena. Verifique se scenes/game/arena.tscn existe no projeto.",
		"creator.ability_loaded": "Habilidade anterior carregada. Edite ou confirme para continuar.",
		"creator.shot_needed": "Escolha um tipo de tiro para continuar.",
		"shot.title": "ESCOLHA SEU TIRO",
		"shot.pick_one": "ESCOLHA UM PARA CONTINUAR",
		"shot.locked": "HABILIDADES NOVAS USAM O PRIMEIRO TIRO",
		"shot.back": "VOLTAR AO DESENHO",
		"shot.confirm": "CONFIRMAR",
		"shot.standard": "PADRÃO",
		"shot.standard_info": "Curva até os inimigos no fim.",
		"shot.charge": "CARREGADO",
		"shot.charge_info": "Segure e cresce. Pouco alcance.",
		"shot.rapid": "RÁPIDO",
		"shot.rapid_info": "Fraco, mas rápido e longe.",
		"shot.damage": "DANO",
		"shot.range": "ALCANCE",
		"shot.rate": "RITMO",
		"stats.life": "HP",
		"stats.damage": "ATQ",
		"stats.rate": "TIRO",
		"stats.pierce": "FURA",
		"stats.size": "TAM.",
		"stats.speed": "VEL.",
		"stats.range": "ALC.",
		"stats.dash": "DASH",
		"stats.move": "PASSO",
		"stats.pickup": "ÍMÃ",
		"stats.per_second": "%s/S",
		"stats.seconds": "%sS",
		"perk.short.vampirism": "VAMPIRO",
		"perk.short.ricochet": "QUICA",
		"perk.short.critical": "CRÍTICO",
		"perk.short.explosion": "EXPLOSÃO",
		"perk.short.shards": "LASCAS",
		"perk.short.overcharge": "CARGA+",
		"perk.short.poison": "VENENO",
		"perk.short.focus": "FOCO",
		"perk.short.momentum": "EMBALO",
		"perk.vampirism": "VAMPIRISMO",
		"perk.vampirism_info": "Acerto rouba 3% da vida máx.",
		"perk.ricochet": "RICOCHETE",
		"perk.ricochet_info": "Quica 1 vez, +1 por perfuração",
		"perk.critical": "CRÍTICO",
		"perk.critical_info": "25% crítico; sobe c/ veloc.",
		"perk.explosion": "EXPLOSÃO",
		"perk.explosion_info": "Cheia explode; tam. = área",
		"perk.shards": "ESTILHAÇOS",
		"perk.shards_info": "Solta estilhaços; + por tiro",
		"perk.overcharge": "SOBRECARGA",
		"perk.overcharge_info": "Segure após cheio: até +60%",
		"perk.poison": "VENENO",
		"perk.poison_info": "Envenena; acumula com o ritmo",
		"perk.focus": "FOCO",
		"perk.focus_info": "Mesmo alvo: +8% dano por acerto",
		"perk.momentum": "EMBALO",
		"perk.momentum_info": "Atira 40% mais rápido andando",
		"hud.hp": "HP: %d / %d",
		"hud.wave": "WAVE: %d",
		"hud.enemies": "INIMIGOS: %d",
		"hud.controls_hint": "ATIRAR: CLIQUE   DASH: ESPAÇO",
		"upgrade.max_hp": "VIDA MÁX. +45",
		"upgrade.move_speed": "VELOCIDADE +20%",
		"upgrade.pickup": "ALCANCE DE COLETA +60%",
		"flask.slots_full": "SLOTS CHEIOS",
		"flask.zigzag": "TIRO EM ZIGUE-ZAGUE",
		"flask.rush": "AVANÇO",
		"flask.burst": "ESTOURO",
		"flask.orbit": "PERSEGUIDOR",
		"creator.palettes": "PALETAS: %d",
		"creator.flask_slots": "FRASCOS: %d/%d",
		"creator.buy_slot": "COMPRAR SLOT (1)",
		"creator.slot_bought": "Mais um slot de frasco liberado.",
		"creator.no_palettes": "Derrote um chefe para ganhar uma paleta.",
		"creator.slots_maxed": "Todos os slots de frasco liberados.",
		"pause.title": "PAUSADO",
		"pause.resume": "CONTINUAR",
		"pause.restart": "REINICIAR",
		"pause.menu": "MENU",
		"progression.wave_complete": "WAVE %d CONCLUÍDA!",
		"progression.choose_path": "ESCOLHA UM UPGRADE PARA SEGUIR",
		"progression.upgrade_ability": "MELHORAR HABILIDADE",
		"progression.upgrade_info": "ESCOLHA 1 ENTRE 3 UPGRADES SORTEADOS",
		"progression.new_ability": "CRIAR NOVA HABILIDADE",
		"progression.new_ability_info": "DESENHE UM NOVO PROJÉTIL (MÁX. 100 PIXELS)",
		"progression.choose_upgrade": "ESCOLHA UM UPGRADE",
		"progression.back": "VOLTAR",
		"progression.reroll": "SORTEAR DE NOVO",
		"progression.need_ink": "FALTAM %d GOTAS",
		"upgrade.damage": "DANO +35%",
		"upgrade.cooldown": "RECARGA -15%",
		"upgrade.count": "+1 PROJÉTIL",
		"upgrade.size": "TAMANHO +30%",
		"upgrade.pierce": "PERFURAÇÃO +1",
		"upgrade.speed": "VELOCIDADE +20%",
		"upgrade.dash": "RECARGA DO DASH -40%",
		"ability.name": "HAB. %d",
		"game_over.wave_reached": "WAVE ALCANÇADA: %d",
		"game_over.best_wave": "RECORDE: %d",
		"game_over.new_record": "NOVO RECORDE!",
		"game_over.coverage": "QUADRO PINTADO: %d%%",
		"game_over.retry": "TENTAR DE NOVO",
		"game_over.new_drawing": "NOVO DESENHO",
		"game_over.save_scenario": "SALVAR QUADRO",
		"game_over.menu": "MENU",
		"scenario.final_canvas": "QUADRO FINAL",
		"scenario.no_canvas": "NENHUM QUADRO DISPONÍVEL",
		"scenario.press_escape": "PRESSIONE ESC PARA VOLTAR",
		"scenario.saved_to": "SALVO EM: %s",
		"scenario.downloaded": "BAIXADO PELO NAVEGADOR: %s",
	},
}


var language_code: String = DEFAULT_LANGUAGE


func _ready() -> void:
	_load_saved_language()
	TranslationServer.set_locale(language_code)


func text(key: String, values: Array = []) -> String:
	var language: Dictionary = TRANSLATIONS.get(language_code, TRANSLATIONS[DEFAULT_LANGUAGE])
	var translated: String = language.get(key, TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key))
	return translated if values.is_empty() else translated % values


func set_language(new_language_code: String) -> void:
	if not TRANSLATIONS.has(new_language_code) or new_language_code == language_code:
		return
	language_code = new_language_code
	TranslationServer.set_locale(language_code)
	_save_language()
	language_changed.emit()


func is_language_selected(candidate_language_code: String) -> bool:
	return language_code == candidate_language_code


func _load_saved_language() -> void:
	var settings: ConfigFile = ConfigFile.new()
	if settings.load(GameManager.SETTINGS_PATH) != OK:
		return
	var saved_language: String = settings.get_value(SETTINGS_SECTION, SETTINGS_KEY, DEFAULT_LANGUAGE)
	if TRANSLATIONS.has(saved_language):
		language_code = saved_language


func _save_language() -> void:
	var settings: ConfigFile = ConfigFile.new()
	settings.load(GameManager.SETTINGS_PATH)
	settings.set_value(SETTINGS_SECTION, SETTINGS_KEY, language_code)
	var save_error: int = settings.save(GameManager.SETTINGS_PATH)
	if save_error != OK:
		push_warning("[LocalizationManager] Não foi possível salvar o idioma selecionado (erro %d)." % save_error)
